package com.ruiaa.toolpck.drawables;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class common_phone extends SVGRenderer {

    public common_phone(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = (int)128.0f;
        mHeight = (int)128.0f;
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        
        final float scaleX = w / 1024.0f;
        final float scaleY = h / 1024.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(686.2271f, 925.18036f);
        mPath.rCubicTo(-55.872517f, -8.66331f, -119.83734f, -41.290405f, -184.97487f, -94.35395f);
        mPath.rCubicTo(-60.350506f, -49.1627f, -120.426765f, -114.45577f, -173.73283f, -188.82047f);
        mPath.rCubicTo(-52.340065f, -73.014946f, -94.687546f, -149.80077f, -122.46212f, -222.05643f);
        mPath.rCubicTo(-29.132504f, -75.78708f, -40.40422f, -142.47083f, -32.593327f, -192.84308f);
        mPath.rCubicTo(4.790096f, -30.89566f, 31.215956f, -64.334236f, 72.50022f, -91.74349f);
        mPath.rCubicTo(34.780132f, -23.089882f, 74.98583f, -37.528732f, 95.60238f, -34.332947f);
        mPath.rCubicTo(16.683985f, 2.586918f, 44.715412f, 42.552143f, 73.155136f, 104.29844f);
        mPath.rCubicTo(26.11375f, 56.698326f, 42.265617f, 109.41804f, 40.427757f, 121.270996f);
        mPath.rCubicTo(-2.940982f, 18.972097f, -13.419637f, 31.639605f, -24.512278f, 45.050034f);
        mPath.rCubicTo(-11.394515f, 13.775748f, -23.175838f, 28.021194f, -26.48521f, 49.366337f);
        mPath.rCubicTo(-3.62762f, 23.39892f, 28.808117f, 78.57764f, 60.371998f, 122.41608f);
        mPath.rCubicTo(29.958311f, 41.606606f, 72.67725f, 91.3925f, 94.47572f, 94.77248f);
        mPath.rCubicTo(18.571983f, 2.879584f, 37.016056f, -3.561106f, 54.851257f, -9.788947f);
        mPath.rCubicTo(18.435884f, -6.437619f, 37.50008f, -13.094226f, 57.311287f, -10.022261f);
        mPath.rCubicTo(16.458857f, 2.552126f, 60.839645f, 36.994568f, 107.92708f, 83.757614f);
        mPath.rCubicTo(54.56064f, 54.185085f, 77.43563f, 89.30802f, 76.25166f, 96.940865f);
        mPath.rCubicTo(-5.647627f, 36.424583f, -29.277815f, 71.60995f, -64.83259f, 96.53359f);
        mPath.cubicTo(756.1783f, 918.9914f, 717.5689f, 930.04004f, 686.2271f, 925.18036f);
        mPath.close();
        mPath.moveTo(686.2271f, 925.18036f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}