package com.ruiaa.toolpck.drawables;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class currencyrate extends SVGRenderer {

    public currencyrate(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = (int)128.0f;
        mHeight = (int)128.0f;
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        
        final float scaleX = w / 1024.0f;
        final float scaleY = h / 1024.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(548.5714f, 526.6286f);
        mPath.lineTo(804.5714f, 526.6286f);
        mPath.rLineTo(0f, -73.14286f);
        mPath.lineTo(579.29144f, 453.48575f);
        mPath.rLineTo(138.97144f, -223.81714f);
        mPath.lineTo(655.36f, 190.17143f);
        mPath.lineTo(512.0f, 421.30286f);
        mPath.lineTo(368.64f, 190.17143f);
        mPath.rLineTo(-61.44f, 38.034286f);
        mPath.lineTo(444.70856f, 453.48572f);
        mPath.rLineTo(-105.325714f, 0f);
        mPath.rLineTo(0f, -54.125713f);
        mPath.rCubicTo(0.0f, -5.851429f, -7.314286f, -10.24f, -11.702857f, -5.851429f);
        mPath.rLineTo(-102.4f, 81.92f);
        mPath.rCubicTo(-7.314286f, 5.851429f, -7.314286f, 17.554285f, 0.0f, 23.405716f);
        mPath.rLineTo(102.4f, 81.92f);
        mPath.rCubicTo(4.388571f, 4.388571f, 11.702857f, 0.0f, 11.702857f, -5.851429f);
        mPath.lineTo(339.38284f, 526.6286f);
        mPath.rLineTo(134.58286f, 0f);
        mPath.rLineTo(0f, 93.622856f);
        mPath.lineTo(219.42857f, 620.25146f);
        mPath.rLineTo(0f, 73.14286f);
        mPath.rLineTo(256.0f, 0f);
        mPath.lineTo(475.4286f, 833.82855f);
        mPath.rLineTo(73.14286f, 0f);
        mPath.rLineTo(0f, -140.43428f);
        mPath.rLineTo(134.58286f, 0f);
        mPath.rLineTo(0f, 46.811428f);
        mPath.rCubicTo(0.0f, 5.851429f, 7.314286f, 10.24f, 11.702857f, 5.851429f);
        mPath.rLineTo(102.4f, -81.92f);
        mPath.rCubicTo(7.314286f, -5.851429f, 7.314286f, -17.554285f, 0.0f, -23.405714f);
        mPath.rLineTo(-102.4f, -81.92f);
        mPath.rCubicTo(-4.388571f, -4.388571f, -11.702857f, 0.0f, -11.702857f, 5.851428f);
        mPath.rLineTo(0f, 54.125713f);
        mPath.rLineTo(-134.58286f, 0f);
        mPath.lineTo(548.5714f, 526.6286f);
        mPath.close();
        mPath.moveTo(548.5714f, 526.6286f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-13882324, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}