package com.ruiaa.toolpck.drawables;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class express extends SVGRenderer {

    public express(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = (int)128.0f;
        mHeight = (int)128.0f;
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        
        final float scaleX = w / 1025.0f;
        final float scaleY = h / 1024.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(768.0f, 1024.0f);
        mPath.rLineTo(-339.13403f, -254.6804f);
        mPath.rLineTo(467.13403f, -641.3196f);
        mPath.rLineTo(-600.41235f, 541.03094f);
        mPath.rLineTo(-294.26804f, -220.37114f);
        mPath.rLineTo(1024.0f, -447.3402f);
        mPath.rLineTo(-257.31958f, 1022.6804f);
        mPath.close();
        mPath.moveTo(768.0f, 1024.0f);
        mPath.rMoveTo(-512.0f, 0.0f);
        mPath.rLineTo(0f, -256.0f);
        mPath.rLineTo(191.34021f, 128.0f);
        mPath.rLineTo(-191.34021f, 128.0f);
        mPath.close();
        mPath.moveTo(256.0f, 1024.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-13882324, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}