package com.ruiaa.toolpck.drawables;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class gradienter extends SVGRenderer {

    public gradienter(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = (int)128.0f;
        mHeight = (int)128.0f;
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        
        final float scaleX = w / 1024.0f;
        final float scaleY = h / 1024.0f;
        final float minScale = Math.min(scaleX, scaleY);
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(512.0f, 42.0f);
        mPath.cubicTo(771.57385f, 42.0f, 982.0f, 252.42616f, 982.0f, 512.0f);
        mPath.cubicTo(982.0f, 771.57385f, 771.57385f, 982.0f, 512.0f, 982.0f);
        mPath.cubicTo(252.42616f, 982.0f, 42.0f, 771.57385f, 42.0f, 512.0f);
        mPath.cubicTo(42.0f, 252.42616f, 252.42616f, 42.0f, 512.0f, 42.0f);
        mPath.close();
        mPath.moveTo(512.0f, 42.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mStrokePaint == null) {
            mStrokePaint = new Paint();
            mStrokePaint.setStyle(Paint.Style.STROKE);
            mStrokePaint.setAntiAlias(true);
        }
        mStrokePaint.setStrokeJoin(Paint.Join.MITER);
        mStrokePaint.setStrokeCap(Paint.Cap.BUTT);
        mStrokePaint.setStrokeMiter(4.0f);
        mStrokePaint.setColor(applyAlpha(-16777216, 1.0f));
        mStrokePaint.setColorFilter(filter);
        mStrokePaint.setStrokeWidth(minScale * 1.0f * 50.0f);
        canvas.drawPath(mRenderPath, mStrokePaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(680.0f, 260.0f);
        mPath.cubicTo(729.7056f, 260.0f, 770.0f, 300.29437f, 770.0f, 350.0f);
        mPath.cubicTo(770.0f, 399.70563f, 729.7056f, 440.0f, 680.0f, 440.0f);
        mPath.cubicTo(630.2944f, 440.0f, 590.0f, 399.70563f, 590.0f, 350.0f);
        mPath.cubicTo(590.0f, 300.29437f, 630.2944f, 260.0f, 680.0f, 260.0f);
        mPath.close();
        mPath.moveTo(680.0f, 260.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mStrokePaint.setStrokeJoin(Paint.Join.MITER);
        mStrokePaint.setStrokeCap(Paint.Cap.BUTT);
        mStrokePaint.setStrokeMiter(4.0f);
        mStrokePaint.setColor(applyAlpha(-16777216, 1.0f));
        mStrokePaint.setColorFilter(filter);
        mStrokePaint.setStrokeWidth(minScale * 1.0f * 50.0f);
        canvas.drawPath(mRenderPath, mStrokePaint);

    }

}