package com.ruiaa.toolpck.drawables;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class qrcode extends SVGRenderer {

    public qrcode(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = (int)128.0f;
        mHeight = (int)128.0f;
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        
        final float scaleX = w / 1024.0f;
        final float scaleY = h / 1024.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(190.06787f, 190.06787f);
        mPath.rLineTo(69.98493f, 0.0f);
        mPath.rLineTo(0.0f, 69.98493f);
        mPath.rLineTo(-69.98493f, 0.0f);
        mPath.rLineTo(0.0f, -69.98493f);
        mPath.close();
        mPath.moveTo(190.06787f, 190.06787f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(386.02692f, 64.09479f);
        mPath.rLineTo(-321.93213f, 0.0f);
        mPath.rLineTo(0.0f, 321.93213f);
        mPath.rLineTo(125.97308f, 0.0f);
        mPath.rLineTo(0.0f, 55.98815f);
        mPath.rLineTo(69.98493f, 0.0f);
        mPath.rLineTo(0.0f, -55.98815f);
        mPath.rLineTo(125.97308f, 0.0f);
        mPath.lineTo(386.02588f, 316.04095f);
        mPath.rLineTo(55.98815f, 0.0f);
        mPath.rLineTo(0.0f, -55.98815f);
        mPath.rLineTo(-55.98815f, 0.0f);
        mPath.lineTo(386.02588f, 64.09479f);
        mPath.close();
        mPath.moveTo(386.02692f, 64.09479f);
        mPath.moveTo(316.04095f, 316.04095f);
        mPath.lineTo(134.07971f, 316.04095f);
        mPath.lineTo(134.07971f, 134.07971f);
        mPath.rLineTo(181.96124f, 0.0f);
        mPath.lineTo(316.04095f, 316.04095f);
        mPath.close();
        mPath.moveTo(316.04095f, 316.04095f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(190.06787f, 763.94617f);
        mPath.rLineTo(69.98493f, 0.0f);
        mPath.rLineTo(0.0f, 69.98493f);
        mPath.rLineTo(-69.98493f, 0.0f);
        mPath.rLineTo(0.0f, -69.98493f);
        mPath.close();
        mPath.moveTo(190.06787f, 763.94617f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(763.94617f, 190.06787f);
        mPath.rLineTo(69.98493f, 0.0f);
        mPath.rLineTo(0.0f, 69.98493f);
        mPath.rLineTo(-69.98493f, 0.0f);
        mPath.rLineTo(0.0f, -69.98493f);
        mPath.close();
        mPath.moveTo(763.94617f, 190.06787f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(512.0f, 506.35648f);
        mPath.lineTo(512.0f, 581.9849f);
        mPath.lineTo(581.9849f, 581.9849f);
        mPath.lineTo(581.9849f, 512.0f);
        mPath.lineTo(637.9731f, 512.0f);
        mPath.lineTo(637.9731f, 442.01508f);
        mPath.lineTo(581.9849f, 442.01508f);
        mPath.lineTo(581.9849f, 386.02692f);
        mPath.lineTo(512.0f, 386.02692f);
        mPath.lineTo(512.0f, 442.37015f);
        mPath.close();
        mPath.moveTo(512.0f, 506.35648f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(512.0f, 762.3017f);
        mPath.lineTo(512.0f, 833.9321f);
        mPath.lineTo(581.9849f, 833.9321f);
        mPath.lineTo(581.9849f, 762.3017f);
        mPath.lineTo(581.9849f, 707.958f);
        mPath.lineTo(637.9731f, 707.958f);
        mPath.lineTo(637.9731f, 637.9731f);
        mPath.lineTo(579.82574f, 637.9731f);
        mPath.lineTo(512.0f, 637.9731f);
        mPath.lineTo(512.0f, 698.3154f);
        mPath.close();
        mPath.moveTo(512.0f, 762.3017f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(581.9849f, 833.9321f);
        mPath.rLineTo(55.98815f, 0.0f);
        mPath.rLineTo(0.0f, 55.98815f);
        mPath.rLineTo(-55.98815f, 0.0f);
        mPath.rLineTo(0.0f, -55.98815f);
        mPath.close();
        mPath.moveTo(581.9849f, 833.9321f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(442.01508f, 889.9203f);
        mPath.lineTo(442.01508f, 959.9052f);
        mPath.lineTo(515.83844f, 959.9052f);
        mPath.lineTo(581.9849f, 959.9052f);
        mPath.lineTo(581.9849f, 889.9203f);
        mPath.lineTo(515.83844f, 889.9203f);
        mPath.close();
        mPath.moveTo(442.01508f, 889.9203f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(707.958f, 707.958f);
        mPath.lineTo(637.9731f, 707.958f);
        mPath.lineTo(637.9731f, 762.3017f);
        mPath.lineTo(637.9731f, 833.9321f);
        mPath.lineTo(707.79736f, 833.9321f);
        mPath.lineTo(763.94617f, 833.9321f);
        mPath.lineTo(763.94617f, 763.94617f);
        mPath.lineTo(707.958f, 763.94617f);
        mPath.close();
        mPath.moveTo(707.958f, 707.958f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(763.94617f, 959.9052f);
        mPath.lineTo(835.771f, 959.9052f);
        mPath.lineTo(899.7573f, 959.9052f);
        mPath.lineTo(959.9052f, 959.9052f);
        mPath.lineTo(959.9052f, 889.9203f);
        mPath.lineTo(899.7573f, 889.9203f);
        mPath.lineTo(833.9321f, 889.9203f);
        mPath.lineTo(833.9321f, 833.9321f);
        mPath.lineTo(763.94617f, 833.9321f);
        mPath.lineTo(763.94617f, 890.2754f);
        mPath.close();
        mPath.moveTo(763.94617f, 959.9052f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(959.9052f, 512.0f);
        mPath.lineTo(959.9052f, 442.01508f);
        mPath.lineTo(899.7573f, 442.01508f);
        mPath.lineTo(833.9321f, 442.01508f);
        mPath.lineTo(833.9321f, 512.0f);
        mPath.lineTo(899.7573f, 512.0f);
        mPath.close();
        mPath.moveTo(959.9052f, 512.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(889.9203f, 763.94617f);
        mPath.rLineTo(69.98493f, 0.0f);
        mPath.rLineTo(0.0f, 69.98493f);
        mPath.rLineTo(-69.98493f, 0.0f);
        mPath.rLineTo(0.0f, -69.98493f);
        mPath.close();
        mPath.moveTo(889.9203f, 763.94617f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(442.01508f, 316.04095f);
        mPath.rLineTo(69.98493f, 0.0f);
        mPath.rLineTo(0.0f, 69.98493f);
        mPath.rLineTo(-69.98493f, 0.0f);
        mPath.rLineTo(0.0f, -69.98493f);
        mPath.close();
        mPath.moveTo(442.01508f, 316.04095f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(763.94617f, 442.01508f);
        mPath.rLineTo(0.0f, -55.98815f);
        mPath.rLineTo(195.95905f, 0.0f);
        mPath.rLineTo(0.0f, -321.93213f);
        mPath.rLineTo(-321.93213f, 0.0f);
        mPath.rLineTo(0.0f, 69.98493f);
        mPath.rLineTo(-58.147327f, 0.0f);
        mPath.rLineTo(-67.82576f, 0.0f);
        mPath.rLineTo(0.0f, 55.98815f);
        mPath.rLineTo(67.82576f, 0.0f);
        mPath.rLineTo(58.147327f, 0.0f);
        mPath.rLineTo(0.0f, 69.98493f);
        mPath.rLineTo(-55.98815f, 0.0f);
        mPath.rLineTo(0.0f, 55.98815f);
        mPath.rLineTo(55.98815f, 0.0f);
        mPath.rLineTo(0.0f, 69.98493f);
        mPath.rLineTo(69.98493f, 0.0f);
        mPath.rLineTo(0.0f, 55.98815f);
        mPath.lineTo(763.94617f, 442.01404f);
        mPath.close();
        mPath.moveTo(763.94617f, 442.01508f);
        mPath.moveTo(707.958f, 134.07971f);
        mPath.rLineTo(181.96124f, 0.0f);
        mPath.lineTo(889.91925f, 316.04095f);
        mPath.lineTo(707.958f, 316.04095f);
        mPath.lineTo(707.958f, 134.07971f);
        mPath.close();
        mPath.moveTo(707.958f, 134.07971f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(707.958f, 581.9849f);
        mPath.rLineTo(55.98815f, 0.0f);
        mPath.rLineTo(0.0f, 55.98815f);
        mPath.rLineTo(-55.98815f, 0.0f);
        mPath.rLineTo(0.0f, -55.98815f);
        mPath.close();
        mPath.moveTo(707.958f, 581.9849f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(833.9321f, 707.958f);
        mPath.lineTo(763.94617f, 707.958f);
        mPath.lineTo(763.94617f, 763.94617f);
        mPath.lineTo(835.771f, 763.94617f);
        mPath.lineTo(889.9203f, 763.94617f);
        mPath.lineTo(889.9203f, 698.3154f);
        mPath.lineTo(889.9203f, 637.9731f);
        mPath.lineTo(959.9052f, 637.9731f);
        mPath.lineTo(959.9052f, 581.9849f);
        mPath.lineTo(899.7573f, 581.9849f);
        mPath.lineTo(833.9321f, 581.9849f);
        mPath.lineTo(833.9321f, 634.3291f);
        mPath.close();
        mPath.moveTo(833.9321f, 707.958f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(442.01508f, 190.06787f);
        mPath.rLineTo(69.98493f, 0.0f);
        mPath.rLineTo(0.0f, 69.98493f);
        mPath.rLineTo(-69.98493f, 0.0f);
        mPath.rLineTo(0.0f, -69.98493f);
        mPath.close();
        mPath.moveTo(442.01508f, 190.06787f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(260.0528f, 512.0f);
        mPath.rLineTo(55.98815f, 0.0f);
        mPath.rLineTo(0.0f, 69.98493f);
        mPath.rLineTo(-55.98815f, 0.0f);
        mPath.rLineTo(0.0f, -69.98493f);
        mPath.close();
        mPath.moveTo(260.0528f, 512.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(442.01508f, 442.01508f);
        mPath.lineTo(387.86578f, 442.01508f);
        mPath.lineTo(316.04095f, 442.01508f);
        mPath.lineTo(316.04095f, 512.0f);
        mPath.lineTo(386.02692f, 512.0f);
        mPath.lineTo(386.02692f, 581.9849f);
        mPath.lineTo(442.01508f, 581.9849f);
        mPath.lineTo(442.01508f, 506.35648f);
        mPath.close();
        mPath.moveTo(442.01508f, 442.01508f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(386.02692f, 833.9321f);
        mPath.lineTo(386.02692f, 707.958f);
        mPath.rLineTo(55.98815f, 0.0f);
        mPath.lineTo(442.01508f, 637.9731f);
        mPath.rLineTo(-54.14927f, 0.0f);
        mPath.lineTo(190.06787f, 637.9731f);
        mPath.rLineTo(0.0f, -67.63031f);
        mPath.rLineTo(0.0f, -58.34278f);
        mPath.rLineTo(-58.14835f, 0.0f);
        mPath.lineTo(64.09479f, 512.0f);
        mPath.rLineTo(0.0f, 69.98493f);
        mPath.rLineTo(69.98493f, 0.0f);
        mPath.rLineTo(0.0f, 55.98815f);
        mPath.lineTo(64.09479f, 637.9731f);
        mPath.rLineTo(0.0f, 321.93213f);
        mPath.rLineTo(321.93213f, 0.0f);
        mPath.rLineTo(0.0f, -69.98493f);
        mPath.rLineTo(55.98815f, 0.0f);
        mPath.rLineTo(0.0f, -55.98815f);
        mPath.lineTo(386.02692f, 833.9321f);
        mPath.close();
        mPath.moveTo(386.02692f, 833.9321f);
        mPath.moveTo(316.04095f, 889.9203f);
        mPath.lineTo(134.07971f, 889.9203f);
        mPath.lineTo(134.07971f, 707.958f);
        mPath.rLineTo(181.96124f, 0.0f);
        mPath.lineTo(316.04095f, 889.9203f);
        mPath.close();
        mPath.moveTo(316.04095f, 889.9203f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(442.01508f, 581.9849f);
        mPath.rLineTo(69.98493f, 0.0f);
        mPath.rLineTo(0.0f, 55.98815f);
        mPath.rLineTo(-69.98493f, 0.0f);
        mPath.rLineTo(0.0f, -55.98815f);
        mPath.close();
        mPath.moveTo(442.01508f, 581.9849f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(637.9731f, 512.0f);
        mPath.rLineTo(69.98493f, 0.0f);
        mPath.rLineTo(0.0f, 69.98493f);
        mPath.rLineTo(-69.98493f, 0.0f);
        mPath.rLineTo(0.0f, -69.98493f);
        mPath.close();
        mPath.moveTo(637.9731f, 512.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(763.94617f, 512.0f);
        mPath.rLineTo(69.98493f, 0.0f);
        mPath.rLineTo(0.0f, 69.98493f);
        mPath.rLineTo(-69.98493f, 0.0f);
        mPath.rLineTo(0.0f, -69.98493f);
        mPath.close();
        mPath.moveTo(763.94617f, 512.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}