package com.ruiaa.toolpck.drawables;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class unitconver extends SVGRenderer {

    public unitconver(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = (int)128.0f;
        mHeight = (int)128.0f;
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        
        final float scaleX = w / 1024.0f;
        final float scaleY = h / 1024.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(827.9063f, 612.3954f);
        mPath.rCubicTo(0.0f, 0.0f, -28.07574f, -31.713205f, -77.05386f, -11.173195f);
        mPath.rCubicTo(-40.49254f, 16.979412f, -26.766254f, 54.2298f, -26.766254f, 54.2298f);
        mPath.rLineTo(93.14656f, 168.05913f);
        mPath.rLineTo(-182.13956f, 0.076867f);
        mPath.rCubicTo(0.0f, 0.0f, -48.26985f, 3.774728f, -48.26985f, 59.50344f);
        mPath.rCubicTo(0.0f, 54.76787f, 52.69795f, 58.80889f, 52.69795f, 58.80889f);
        mPath.rLineTo(384.5089f, -0.156479f);
        mPath.rLineTo(-196.12389f, -329.34845f);
        mPath.close();
        mPath.moveTo(827.9063f, 612.3954f);
        mPath.moveTo(602.9325f, 474.10034f);
        mPath.rCubicTo(-0.049415f, -0.032943f, -0.079612f, -0.05765f, -0.129027f, -0.087848f);
        mPath.rLineTo(0.129027f, 0.087848f);
        mPath.close();
        mPath.moveTo(602.9325f, 474.10034f);
        mPath.moveTo(601.074f, 472.82108f);
        mPath.rLineTo(-0.938877f, -0.647881f);
        mPath.rLineTo(0.938877f, 0.647881f);
        mPath.close();
        mPath.moveTo(601.074f, 472.82108f);
        mPath.moveTo(601.61755f, 473.19443f);
        mPath.rLineTo(-0.540815f, -0.373355f);
        mPath.rLineTo(0.540815f, 0.373355f);
        mPath.close();
        mPath.moveTo(601.61755f, 473.19443f);
        mPath.moveTo(602.80347f, 474.0125f);
        mPath.rLineTo(-0.565523f, -0.389826f);
        mPath.rLineTo(0.565523f, 0.389826f);
        mPath.close();
        mPath.moveTo(602.80347f, 474.0125f);
        mPath.moveTo(602.238f, 473.62268f);
        mPath.rLineTo(-0.623173f, -0.42826f);
        mPath.rCubicTo(0.225111f, 0.150989f, 0.433751f, 0.296488f, 0.623173f, 0.42826f);
        mPath.close();
        mPath.moveTo(602.238f, 473.62268f);
        mPath.moveTo(600.039f, 472.1073f);
        mPath.rCubicTo(-0.178442f, -0.123537f, -0.219621f, -0.150989f, 0.0f, 0.0f);
        mPath.close();
        mPath.moveTo(600.039f, 472.1073f);
        mPath.moveTo(600.1378f, 472.1732f);
        mPath.cubicTo(600.10596f, 472.14966f, 600.073f, 472.12766f, 600.039f, 472.1073f);
        mPath.rLineTo(0.098829f, 0.065886f);
        mPath.close();
        mPath.moveTo(600.1378f, 472.1732f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(679.47577f, 480.42816f);
        mPath.rCubicTo(47.764725f, -35.72128f, 18.154383f, -74.942764f, 18.154383f, -74.942764f);
        mPath.lineTo(511.12564f, 72.82068f);
        mPath.rLineTo(-1.529108f, -2.72604f);
        mPath.rLineTo(-191.49814f, 332.05527f);
        mPath.rLineTo(47.17998f, 32.786602f);
        mPath.rLineTo(44.657093f, 31.037872f);
        mPath.rLineTo(97.57466f, -157.67657f);
        mPath.rLineTo(3.618248f, 6.286638f);
        mPath.rLineTo(91.80688f, 159.51588f);
        mPath.rCubicTo(11.112799f, 16.85313f, 44.81632f, 27.889065f, 76.540504f, 6.327817f);
        mPath.close();
        mPath.moveTo(679.47577f, 480.42816f);
        mPath.moveTo(334.94604f, 474.10034f);
        mPath.rCubicTo(44.38257f, 29.206787f, 74.98669f, -8.12596f, 74.98669f, -8.12596f);
        mPath.rLineTo(-91.83433f, -63.824474f);
        mPath.rCubicTo(0.0f, 0.0f, -24.276306f, 44.887695f, 16.847641f, 71.95043f);
        mPath.close();
        mPath.moveTo(334.94604f, 474.10034f);
        mPath.moveTo(383.32568f, 824.68335f);
        mPath.rLineTo(0.005491f, -0.167461f);
        mPath.rLineTo(-2.745257f, 0f);
        mPath.rLineTo(-173.26413f, 0.054905f);
        mPath.rLineTo(99.543015f, -171.94092f);
        mPath.rCubicTo(0.0f, 0.0f, 11.233591f, -46.37837f, -33.58822f, -64.23627f);
        mPath.rCubicTo(-45.535576f, -18.143402f, -76.878174f, 22.93113f, -76.878174f, 22.93113f);
        mPath.lineTo(-0.002745f, 941.8976f);
        mPath.rLineTo(379.56744f, -0.236092f);
        mPath.rLineTo(0.008236f, -0.280016f);
        mPath.rCubicTo(10.906905f, -1.435769f, 50.77078f, -10.127252f, 50.77078f, -60.488987f);
        mPath.rCubicTo(0.0f, -48.387897f, -36.62996f, -55.24006f, -47.018013f, -56.209133f);
        mPath.close();
        mPath.moveTo(383.32568f, 824.68335f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}