package com.ruiaa.toolpck.drawables;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class zodiac extends SVGRenderer {

    public zodiac(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = (int)128.0f;
        mHeight = (int)128.0f;
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        
        final float scaleX = w / 1024.0f;
        final float scaleY = h / 1024.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(511.0722f, 105.54644f);
        mPath.rLineTo(91.04188f, 152.6485f);
        mPath.rLineTo(-180.0813f, 0.0f);
        mPath.lineTo(511.0722f, 105.54644f);
        mPath.close();
        mPath.moveTo(511.0722f, 105.54644f);
        mPath.moveTo(868.5582f, 705.5956f);
        mPath.rLineTo(-169.38795f, 0.0f);
        mPath.rLineTo(86.29509f, -133.81787f);
        mPath.lineTo(868.5582f, 705.5956f);
        mPath.close();
        mPath.moveTo(868.5582f, 705.5956f);
        mPath.moveTo(151.59392f, 705.5956f);
        mPath.rLineTo(73.07945f, -133.81787f);
        mPath.rLineTo(88.29874f, 133.81787f);
        mPath.lineTo(151.59392f, 705.5956f);
        mPath.close();
        mPath.moveTo(151.59392f, 705.5956f);
        mPath.moveTo(354.62427f, 766.5153f);
        mPath.rLineTo(156.44893f, 256.2205f);
        mPath.rLineTo(156.38718f, -256.2205f);
        mPath.rLineTo(312.0896f, 0.0f);
        mPath.rLineTo(-156.38696f, -257.77664f);
        mPath.rLineTo(156.38597f, -250.54494f);
        mPath.rLineTo(-312.0884f, 0.0f);
        mPath.lineTo(511.0722f, 0.043371f);
        mPath.rLineTo(-156.44792f, 258.15057f);
        mPath.lineTo(42.533466f, 258.19394f);
        mPath.rLineTo(156.44913f, 250.54494f);
        mPath.lineTo(42.533466f, 766.5153f);
        mPath.lineTo(354.62427f, 766.5153f);
        mPath.close();
        mPath.moveTo(354.62427f, 766.5153f);
        mPath.moveTo(878.53546f, 319.1802f);
        mPath.rLineTo(-83.08707f, 130.57007f);
        mPath.rLineTo(-86.302086f, -130.57007f);
        mPath.lineTo(878.53546f, 319.1802f);
        mPath.close();
        mPath.moveTo(878.53546f, 319.1802f);
        mPath.moveTo(511.0722f, 921.2212f);
        mPath.rLineTo(-81.06224f, -154.7059f);
        mPath.rLineTo(162.12468f, 0.0f);
        mPath.lineTo(511.0722f, 921.2212f);
        mPath.close();
        mPath.moveTo(511.0722f, 921.2212f);
        mPath.moveTo(262.33563f, 508.73868f);
        mPath.rLineTo(122.00069f, -189.55869f);
        mPath.rLineTo(255.44002f, 0.0f);
        mPath.rLineTo(122.02986f, 189.55869f);
        mPath.rLineTo(-128.7663f, 196.85693f);
        mPath.lineTo(388.32483f, 705.5956f);
        mPath.lineTo(262.33563f, 508.73868f);
        mPath.close();
        mPath.moveTo(262.33563f, 508.73868f);
        mPath.moveTo(145.60878f, 319.1802f);
        mPath.rLineTo(167.36333f, 0.0f);
        mPath.rLineTo(-82.31239f, 128.57463f);
        mPath.lineTo(145.60878f, 319.1802f);
        mPath.close();
        mPath.moveTo(145.60878f, 319.1802f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}